CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(100) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          account_number VARCHAR(30) NOT NULL,
                          balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT uq_accounts_account_number
                              UNIQUE (account_number),

                          CONSTRAINT chk_accounts_balance_non_negative
                              CHECK (balance >= 0),

                          CONSTRAINT chk_accounts_status
                              CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),

                          CONSTRAINT fk_accounts_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id)
);

CREATE INDEX idx_accounts_user_id
    ON accounts(user_id);
