create table transfers(
    id bigint generated by default as identity primary key,
    from_account_id bigint not null,
    to_account_id bigint not null,
    amount numeric(19,2) not null check (amount > 0),
    currency varchar(3) not null check (currency in ('VND', 'USD', 'SGD')),
    status varchar(20) not null default 'PENDING' check (status in ('PENDING', 'COMPLETED', 'FAILED')),
    created_at timestamp not null default current_timestamp,

    constraint fk_transfer_from_account foreign key (from_account_id) references accounts(id),
    constraint fk_transfer_to_account foreign key (to_account_id) references accounts(id),
    constraint transfer_same_account check (from_account_id <> to_account_id)
);

create index idx_transfer_from_account_id on transfers(from_account_id);
create index idx_transfer_to_account_id on transfers(to_account_id);
