create table ledger_entries (
    id bigint generated by default as identity primary key,
    transfer_id bigint not null,
    account_id bigint not null,
    entry_type varchar(10) not null check (entry_type in ('DEBIT', 'CREDIT')),
    amount numeric(19,2) not null check (amount > 0),
    currency varchar(3) not null check (currency in ('VND', 'USD', 'SGD')),
    created_at timestamp not null default current_timestamp,

    constraint fk_ledger_entry_transfer foreign key (transfer_id) references transfers(id),
    constraint fk_ledger_entry_account foreign key (account_id) references accounts(id)
);

create index idx_ledger_entries_transfer_id on ledger_entries(transfer_id);
create index idx_ledger_entries_account_id on ledger_entries(account_id);
